[package]
name = "comarc_intepreter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
anyhow = "1.0.96"
asm_virtual_machine = { path = "asm_virtual_machine" }
