[package]
name = "asm_virtual_machine"
version = "0.1.2"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
pest = "2.7.15"
pest_derive = "2.7.15"
strum = { version = "0.27.1", features = ["derive"] }
yew = { version = "0.21.0", features = ["csr"] }
